spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/omsdb
spring.datasource.username=omsuser
spring.datasource.password=omspass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
